vmware/terraform-provider-hcx

.github/workflows/release.yaml
.gitignore
.goreleaser.yml
LICENSE
data_source_compute_profile.go
data_source_network_backing.go
docs/index.md
go.mod
hcx/network_profile.go
hcx/site_pairing.go
hcx/utils.go
provider.go
resource_activation.go
resource_compute_profile.go
resource_l2_extension.go
resource_location.go
resource_network_profile.go
resource_rolemapping.go
resource_service_mesh.go
resource_site_pairing.go
resource_sso.go
resource_vcenter.go
resource_vmc.go

- Resolves int overflow error caused by HCX operations taking an extended period of time
- Adds Apache 2.0 license

Resolve int overflow, add license

---

LICENSE
NOTICE

Changes the license to Mozilla Public License Version 2.0.

chore: change license to MPL-2.0

---

CODE-OF-CONDUCT.md

Updates the Code of Conduct based on the [Contributor Covenant Code of Conduct v2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).

chore: add code of conduct

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Adds issue templates in the form format for:
- Bugs
- Documentation
- Enhancements

chore: add issue templates

---

.github/workflows/lock.yml

Adds workflow to lock issues and pull requests closed after x days.

chore(gh): add lock workflow

---

data_source_compute_profile.go
data_source_network_backing.go
docs/guides/cloud-to-cloud.md
docs/guides/lab.md
docs/guides/vmc.md
docs/index.md
go.mod
provider.go
resource_activation.go
resource_compute_profile.go
resource_l2_extension.go
resource_location.go
resource_network_profile.go
resource_rolemapping.go
resource_service_mesh.go
resource_site_pairing.go
resource_sso.go
resource_vcenter.go
resource_vmc.go

Updates `hcx "github.com/adeleporte/terraform-provider-hcx/hcx"` to  `hcx "github.com/vmware/terraform-provider-hcx/hcx"`.

chore: update hcx import

---

hcx/activation.go
hcx/certificate.go
hcx/client.go
hcx/compute_profile.go
hcx/jobs.go
hcx/l2_extension.go
hcx/location.go
hcx/network_profile.go
hcx/role_mapping.go
hcx/service_mesh.go
hcx/site_pairing.go
hcx/sso.go
hcx/utils.go
hcx/vcenter.go
hcx/vmc.go
main.go
provider.go
resource_activation.go
resource_compute_profile.go
resource_l2_extension.go
resource_location.go
resource_network_profile.go
resource_rolemapping.go
resource_service_mesh.go
resource_site_pairing.go
resource_sso.go
resource_vcenter.go
resource_vmc.go

As discussed with Chip Childers:
- Adds the Broadcom copyright, as needed.
- Adds the SPDX-License-Identifier, as needed.
**Go**:
```go
// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0
```

chore: add copyright and spdx

---

docs/index.md

docs: update docs landing

---

.github/workflows/release.yaml
.goreleaser.tmpl
.goreleaser.yml
terraform-registry-manifest.json

Updates release workflow.
Closes #12

chore(gh): update release workflow

---

Makefile
scripts/gofmtcheck.sh

refactor: update makefile

---

CHANGELOG.md

chore: add `CHANGELOG.md`

---

README.md
docs/build.md
docs/install.md

Adds installation and build documentation with links from the project `README.md`.

docs: add install and build

---

docs/guides/lab.md
docs/resources/l2_extension.md

Updates documentation for `r/hcx_l2_extension` to refer to use of `service_mesh_id` instead of `service_mesh_name`.
Closes #8

docs: update `r/hcx_l2_extension`

---

docs/data-sources/compute_profile.md
docs/data-sources/network_backing.md
docs/guides/cloud-to-cloud.md
docs/guides/vmc.md
docs/resources/activation.md
docs/resources/compute_profile.md
docs/resources/l2_extension.md
docs/resources/location.md
docs/resources/network_profile.md
docs/resources/rolemapping.md
docs/resources/service_mesh.md
docs/resources/site_pairing.md
docs/resources/vcenter.md
docs/resources/vmc.md

Documentation cleanup. Generally, idiomatic markdown stucture and formatting.

docs: update docs

---

hcx/client.go

Technical Debt: unused
This pull request involves removing several unused structs from the `hcx/client.go` file to clean up the codebase.
Codebase simplification:
* Removed the `updateConfigurationModule` struct, which was not being used.
* Removed the `updateConfigurationModuleBody` struct, which was not being used.
* Removed the `enterprise_get_object_groups` struct, which was not being used.
Ref: #42
**Breaking …

chore: unused

---

docs/guides/cloud-to-cloud.md
docs/guides/lab.md
docs/guides/vmc.md
docs/resources/vmc.md

Clarifies "VMC" as VMware Cloud on AWS.

docs: update vmc

---

docs/guides/cloud-to-cloud.md
docs/guides/lab.md
docs/guides/vmc.md
docs/resources/network_profile.md
docs/resources/rolemapping.md
docs/resources/site_pairing.md
docs/resources/vcenter.md

Updates to use `example.com` instead of `corp.local` and `cloud-garage.net`.

docs: use `example.com`

---

docs/resources/sso.md

Adds the documentation missing for `r/hcx_sso`.

docs: add `r/sso`

---

.github/workflows/golangci-lint.yml
.golangci.yml
README.md
go.mod

- Upgrades to golangci-lint configuration to support v2.
- Updates workflow to v7 that supports v2.

chore: upgrade to golangci-lint v2

---

.golangci.yml
hcx/resource_location.go
hcx/resource_rolemapping.go
hcx/resource_service_mesh.go
hcx/resource_sso.go
hcx/validators/validators.go
main.go

UIn order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware/terraform-provider-hcx/blob/main/CONTRIBUTING.md) for making a pull request.
Updates formatting of go module imports.

chore: update go module imports

---

.golangci.yml
hcx/client.go

chore: ignore gosec G402

---

.golangci.yml

Removes revive: redefines-builtin-id exclusion.

chore: update `.golangci.yml`
